menu_settings:
    menu_items:
        - title: 'About'
          url: '/about/'
        - title: 'Archive'
          url: '/archive/'

cv:
    employment:
        - title: 'Graphic Designer'
          company: 'Self-employed'
          time: '2014 - Present'
        - title: 'Graphic Designer, Jr.'
          company: 'Themenoid, DE'
          time: '2015 - 2016'
        - title: 'Web Designer'
          company: 'Witness Performance, AU'
          time: '2017 - 2018'
        - title: 'Graphic Designer, Sr.'
          company: 'Cattiensa, VN'
          time: '2018 - 2019'
    education:
        - title: 'Bachelor of Design, Digital Media'
          institute: 'RMIT University, AU'
          time: '2014 - 2018'
        - title: 'Master of Design, Multimedia Design'
          institute: 'Monash University, AU'
          time: '2019 - 2021'

works:
    - title: 'Hyperion, The First Principle'
      category: 'Identity/ Art Direction'
      year: '2018'
      image: '01.png'
    - title: 'The Sound of SaigoiiSound'
      category: 'Identity/ Web Design'
      year: '2019'
      image: '02.png'
    - title: 'Theia of the subtlety'
      category: 'Identity/ Print/ Website'
      year: '2018'
      image: '03.png'
    - title: 'The first drop from a Deadend'
      category: 'Web Design'
      year: '2019'
      image: '04.png'
    - title: "Hey! There's a Spiderum in the corner"
      category: 'Web Design/ UI'
      year: '2020'
      image: '05.png'
    - title: 'Cherish the Precious moments'
      category: 'Identity'
      year: '2018'
      image: '06.png'
    - title: 'Back to the good old Thom'
      category: 'Art Direction'
      year: '2018'
      image: '07.png'
